name: Android CI

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Show Gradle version
      run: ./gradlew --version

    - name: List project files
      run: ls -R

    - name: Build with Gradle (with debug info)
      run: ./gradlew assembleDebug --info --stacktrace

    - name: Upload build reports
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: app/build/reports/

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
